apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-cpu
  namespace: generative-ai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
